HTML/CSS & JavaScript capstone project - Conference page
Dorcas126/final-capstone-project-1 pull request #1
Opened 2023-05-30 10:26 UTC by Dorcas126

This is my first capstone project at Microverse which I implemented a conference page by using the following technologies:
 - HTML
 - CSS
 - JavaScript

## Learning objectives
- Understand how to use medium-fidelity wireframes to create a UI.
- Follow written requirements (e.g. user stories).
- Use semantic HTML tags.
- Apply best practices in HTML code.
- Use CSS selectors correctly.
- Use CSS box model.
- Use Flexbox to place elements in the page.
- Use images and backgrounds to enhance the look of a website.
- Demonstrate ability to create UIs adaptable to different screen sizes using media queries.
- Use GitHub Pages to deploy web pages.
- Apply JavaScript best practices and language style guides in code.
- Use JavaScript to manipulate DOM elements.
- Use JavaScript events.
- Use objects to store and access data.

2023-05-30 12:28 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Dorcas126 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 12:28 UTC, joel-kalema commented on about.html
> +                                <li class="nav-item about"><a href="about.html">About</a></li>
- [ ]  You did great work @Dorcas126  😃, however, in this `about.html` page we are not supposed to have again the `about` button in your navbar. What do you think if we change it to this `<li class="nav-item about"><a href="index.html"> Home </a></li>` to facilitate the user to go back to the `home` page 👍. Kindly fix it and make sure it is the same for the `mobile menu` 💪.

2023-05-30 12:28 UTC, joel-kalema commented on about.html
> +                            <img  class="md-footer-img" src="img/creative-logo2.png" alt="">
- [ ] For the page's accessibility, Kindly make sure all images contain `alt` attributes 👍

2023-05-30 12:28 UTC, joel-kalema commented on index.html
> +                    </div>
- [ ] Good job working on the activity section 👍, however, I'll suggest you display the `lecture` bloc as `display raw` to stick the design as much as possible 😃. 
- [ ] Also, what do you think if we make our `background` look like what we have on the `template`? You don't need to have the same image but let's get something that can have the color 👍 

> | | template | | Your project | |
> |-|---------|-|--------|-|
> | |![Screenshot 2023-05-30 132715](https://github.com/Dorcas126/final-capstone-project-1/assets/57408419/3225f31b-8c5b-4b82-9cc0-80cfcc278f0d)| |![Screenshot 2023-05-30 132805](https://github.com/Dorcas126/final-capstone-project-1/assets/57408419/53e496e6-301b-4099-bb0f-8bd52cf91619)| |

- [ ] Your section is good ❤️, however, let's add some `hover` to stick the design 💪.


![Screenshot 2023-05-30 133904](https://github.com/Dorcas126/final-capstone-project-1/assets/57408419/24aa7f2b-1f7f-4345-a5f7-014211861a90)

2023-05-30 12:28 UTC, joel-kalema commented on index.html
> +            </div>
- [ ] Now let's talk about Speakers 😃. I like the way you have done using `JavaScript`,  However, currently, when we are clicking on the `see more speakers` button, we are just changing the value of the button, but we suppose to display all speakers then when we click again on `see less` we are supposed to display only two speakers. Kindly fix it 💪

2023-05-30 12:28 UTC, joel-kalema commented on style.css
> +}
- [ ] Kindly make sure you stuck the design using a `background-image`, `font-size`, `font-weight` on your text, let's take an example from this.

```` buch
  color: transparent;
  font-size: 2.05rem;
  font-weight: 1000;
  text-transform: uppercase;
  background-image: url(....image url....);
  background-position: -700px;
  -webkit-background-clip: text;

````
#### Templete
![Screenshot 2023-05-30 135309](https://github.com/Dorcas126/final-capstone-project-1/assets/57408419/6141f3d0-3d9f-4242-9661-c4de3a3a12d2)

#### Your design

![Screenshot 2023-05-30 142349](https://github.com/Dorcas126/final-capstone-project-1/assets/57408419/5b78e128-9eda-44c1-a1a2-c04c5407f43b)

2023-05-30 12:28 UTC, joel-kalema commented on README.md
> +Thank you
- [ ] Kindly make sure you gave your Acknowledgments to the Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07). as it is [required](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=Original%20design%20idea%20by%20Cindy%20Shin%20in%20Behance.) 😃

2023-05-30 16:37 UTC, Dorcas126 commented on index.html
> +            </div>
Thank you for your feedback, I appreciate it, but the `more` button functionality is not part of the project requirements. Thank you.

2023-05-30 18:03 UTC, usorfaitheloho requested changes
> Hi @Dorcas126  ,
> 
> Great job for implemented the some of the Project Requirement , but there are some changes that need to be implemented in order to proceed to the next project 👍
> 
> ## Highlights 👏🏻
> ✔️ Implemented review coments ✔️ You used correct Git Hub-Flow. ✔️ Good README ✔️ Good Commit Messages
> 
> ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) 

> ## Required Changes ♻️
> _Check the comments below the review._
> 
> * [ ]  Kindly I recommend you to update your READEME file to include the **"Feature section "**  including 1-3 potential features to be added and please before push the READEME file to main branch kindly make sure that you update in your feature branch(here).
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 18:03 UTC, usorfaitheloho commented on index.html
> +                          <p class="p-tag">Get opportnunities to network with CC affiliates around the world</p>
As suggested by the previous reviewer, kindly use the background color that was used in the design given as we're always advised to make our design as really close as possible to any design given. For your design, you used a really dark colour while the design given has something similar to `#262932` for the background, kindly implement this change 😄

Design given : 
![image](https://github.com/Dorcas126/final-capstone-project-1/assets/20537712/80286179-b702-4e90-a7cb-c1fa8b8f1e95)

Your design :
![image](https://github.com/Dorcas126/final-capstone-project-1/assets/20537712/a02c2c34-94fb-4cfc-b443-56981c055878)

2023-05-30 18:03 UTC, usorfaitheloho commented on index.html
> +            </div>
Hi @Dorcas126 , the mobile view should also contain the same number of speakers as the desktop view, although the `more` button was not stated in the `requirements` it is however visible in the design and has a functionality, please kindly make the required changes for the `speaker` section and resubmit for a review 😄

2023-05-31 11:10 UTC, mckent05 approved these changes
Hi @Dorcas126, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- Good job creating your first capstone project, keep going 🚀 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 11:10 UTC, mckent05 commented on about.html
> +                        </div>
**OPTIONAL** - The sponsor section is missing in the mobile version of this page, though you have done well so far 👏, Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏

Your project:
![awrhwrh](https://github.com/Dorcas126/final-capstone-project-1/assets/73607512/387a8d3d-d851-4adb-84e4-2f83be7dffc9)
Design template:
![awrgawrg](https://github.com/Dorcas126/final-capstone-project-1/assets/73607512/60962f59-fe01-4343-aaac-a4544c2bf7c8)

2023-05-31 11:10 UTC, mckent05 commented on about.html
> +                            <h1 class="intro">CREATIVE ANNUAL GLOBAL LEARNING SUMMIT</h1>
**OPTIONAL** - Please note that in order to improve the semantics of your page, I advise that your `hx` tag follow an ascending hierarchy i.e an `h2` tag should only be used after an `h1` tag. I suggest using a `p` tag in place of the `h3` tag. Please fix this 😄

2023-05-31 11:18 UTC, merged